### ISSUE TITLE
.01 skill listing fee

### ISSUE THREAD

**Issue by seiyria** [CryptoBlades/cryptoblades#648] opened 2021-08-09 18:06 UTC

**Comment by brian-man** [comment] 2021-08-10 03:54
@seiyria This is duplicate of https://github.com/CryptoBlades/cryptoblades/pull/545 isn't it?

**Comment by seiyria** [comment] 2021-08-10 08:24
@brian-man not sure if this was put out in issue form before. we talked about it again today so I wanted to make sure it was covered

**Closed** 2021-08-31 18:09 UTC
Labels: priority-medium, type-frontend, type-solidity
