### ISSUE TITLE
Stake time not working as intended?

### ISSUE THREAD

**Issue by Giovanny-DS** [CryptoBlades/cryptoblades#607] opened 2021-08-05 05:39 UTC
![image](https://user-images.githubusercontent.com/61195397/128296975-3e070a69-24c4-4370-827c-2d7da4fa0aa1.png)
![image](https://user-images.githubusercontent.com/61195397/128297020-1137c91b-622f-4b49-9254-f4ef5b7f5921.png)

**Comment by OPPandaDeFi** [comment] 2021-08-05 05:54
I just tried. Had some that was ready. I left 0.001 in there. The UI says I need to wait 7 days now. And contract throws an error when I try withdraw it directly now(which it should if its locked).

This has been the behavior for the last while at least for me. Adding more doesn't reset the time though, which I believe was intended(?). It does seem to reset the 7 day lock when you unstake some. or initially put skill into it

**Comment by seiyria** [comment] 2021-08-05 12:09
Closing since it seems to be intended behavior

**Closed by seiyria** 2021-08-05 12:09 UTC
